[phases.setup]
nixPkgs = ["python3", "gcc", "sqlite", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --no-cache-dir --upgrade pip",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 app:app"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"