[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-login>=0.6.3",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "authlib>=1.6.4",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
